version: "3.9"

services:
  frost-server:
    image: ${REGISTRY:-0x6a6f6e6e79}/frost-server:latest # Pin to a specific version tag in production for predictable deployments
    networks:
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        caddy: frost.example.com
        caddy.reverse_proxy: "{{upstreams 2744}}"

  telegram-notification-service:
    image: ${REGISTRY:-0x6a6f6e6e79}/telegram-multisig-ceremony-notification-service:latest
    networks:
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        caddy: tgns.example.com
        caddy.reverse_proxy: "{{upstreams 3000}}"

volumes:
  caddy_server_data:

networks:
  web:
    external: true
    attachable: true
  caddy_controller:
    external: true
    attachable: true